// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAejssX6S-DM4_3RnQfJutTsHD-0Ljyv4o',
    appId: '1:925750662069:web:036d345c25caccd69a7ffc',
    messagingSenderId: '925750662069',
    projectId: 'sihmav',
    authDomain: 'sihmav.firebaseapp.com',
    storageBucket: 'sihmav.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx5yltzE4TI5PnY7qFQyh4yhY9R5ffDXo',
    appId: '1:925750662069:android:e89ba52692a56c849a7ffc',
    messagingSenderId: '925750662069',
    projectId: 'sihmav',
    storageBucket: 'sihmav.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPZRDtRP-OzPJSwSwCL2MRuaBKvy_zsLU',
    appId: '1:925750662069:ios:c586177753cab25b9a7ffc',
    messagingSenderId: '925750662069',
    projectId: 'sihmav',
    storageBucket: 'sihmav.appspot.com',
    iosBundleId: 'com.example.mav',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPZRDtRP-OzPJSwSwCL2MRuaBKvy_zsLU',
    appId: '1:925750662069:ios:c9b2c81aecc93fbf9a7ffc',
    messagingSenderId: '925750662069',
    projectId: 'sihmav',
    storageBucket: 'sihmav.appspot.com',
    iosBundleId: 'com.example.mav.RunnerTests',
  );
}
